import { ReactNode } from "react";

interface AuthLayoutProps {
  children: ReactNode;
}

// export const metadata: Metadata = {
//   title: "AuthLayout",
//   description: "Generated by create next app",
// };

export default function AuthLayout({ children }: AuthLayoutProps) {
  return (
    <div className="min-h-screen flex flex-col md:flex-row">
      {/* ส่วนด้านซ้าย: รูปภาพหรือ banner */}
      <div className="hidden md:flex md:w-1/2 bg-primary relative ">
        <div className="absolute inset-0 flex items-center justify-center p-10 flex-col">
          <h1 className="text-4xl font-bold text-white mb-4">
            Package Management
          </h1>
          <p className="text-muted-foreground text-center max-w-md">
            ระบบจัดการพัสดุที่ทันสมัย ช่วยให้คุณบริหารพัสดุได้อย่างมีประสิทธิภาพ
            รวดเร็ว และแม่นยำ
          </p>
        </div>
      </div>

      {/* ส่วนด้านขวา: แบบฟอร์ม authentication */}
      <div className="flex-1 flex items-center justify-center p-6 md:p-10 bg-background">
        <div className="w-full max-w-md">
          {/* แบบฟอร์ม (children) */}
          {children}
        </div>
      </div>
    </div>
  );
}
